walkingcode:
    resource: "@walkingcodeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@walkingcodeBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"